# ARRAYS
Collection of similar types of elements.

# Creation of Array

In [1]:
cars = ["Ford", "Volvo", "BMW"]
print(cars)

['Ford', 'Volvo', 'BMW']


# Access the elements of an Array

In [3]:
x = cars[0]
print(x)

Ford


# Modify the values

In [4]:
cars[0] = "Toyota"
print(cars)

['Toyota', 'Volvo', 'BMW']


# Length of an array

In [6]:
x = len(cars)
print(x)

3


# Print each item in car array

In [8]:
cars = ["Ford", "Volvo", "BMW"]
for x in cars:
  print(x)

Ford
Volvo
BMW


# Adding array elements

In [9]:
cars = ["Ford", "Volvo", "BMW"]
cars.append("Honda")
print(cars)


['Ford', 'Volvo', 'BMW', 'Honda']


# Remove array elements

In [10]:
cars = ["Ford", "Volvo", "BMW"]
cars.pop(1)
print(cars)

['Ford', 'BMW']


# DAY-4 REVISION

In [11]:
lst=[1,2,3,4]
print(lst*3)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [4]:
import numpy as np

# To print array elements and to know datatype

In [15]:
x=[10,20,30,40]
arr=np.array(x)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40]


# To give the dimension or shape to a given array 

In [16]:
arr.shape

(4,)

In [19]:
x1=[1,2,3,4,5]
x2=[4,5,6,7,8]
x3=[5,6,7,8,9]
arr=np.array([x1,x2,x3])
print(arr)
print(type(arr))

[[1 2 3 4 5]
 [4 5 6 7 8]
 [5 6 7 8 9]]
<class 'numpy.ndarray'>


In [20]:
arr.shape

(3, 5)

# To change the dimension or shape to a given array 

In [21]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 4],
       [5, 6, 7],
       [8, 5, 6],
       [7, 8, 9]])

In [23]:
arr.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

# To print array

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [ ]:
arr[2,5]

# To create an array evenly with space values

In [25]:
arr=np.arange(0,7)
print(arr)

[0 1 2 3 4 5 6]


In [26]:
arr=np.arange(0,20,5)
print(arr)

[ 0  5 10 15]


# Some basic slicing operation on arrays

In [2]:
import numpy as np

In [8]:
x1=[1,2,3,4,5]
x2=[4,5,6,7,8]
x3=[5,6,7,8,9]
arr=np.array([x1,x2,x3])
print(arr)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [5 6 7 8 9]]


In [3]:
arr=np.arange(0,7)
print(arr)

[0 1 2 3 4 5 6]


In [4]:
arr[1:5]


array([1, 2, 3, 4])

In [6]:
arr=np.array([1,2,3,4,5,6,7])
arr[1:5]

array([2, 3, 4, 5])

# linspace() is a function in Python's NumPy library that allows you to create evenly spaced arrays with a specified number of elements.

In [5]:
np.linspace(5,100,20)

array([  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
        60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [14]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[1:6]

array([2, 3, 4, 5, 6])

In [17]:
arr[1:5]

array([2, 3, 4, 5])

In [20]:
arr[3:]=100
print(arr)

[  1   2   3 100 100 100 100 100 100 100]


# Copy one array to another array

In [22]:
arr1=arr.copy()
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

# Which is less than 2 will give True & Other will give False.

In [24]:
arr1<2

array([ True, False, False, False, False, False, False, False, False,
       False])

# Multiply each element in an array by 2

In [25]:
arr1*2

array([  2,   4,   6, 200, 200, 200, 200, 200, 200, 200])

# To find the position which is less than 2 in an array

In [26]:
arr1[arr1<2]

array([1])

# To print data in tabular (rows, columns and values) format

In [28]:
import pandas as pd

In [29]:
import numpy as np

In [30]:
table=pd.DataFrame(np.arange(0,20).reshape(4,5),index=['R1','R2','R3','R4'],columns=['C1','C2','C3','C4','C5'])

In [31]:
print(table)

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19
