# NUMPY 
contains multidimensional array and matrix data structures.

# Array Vs List
1. In Arrays each no. is multiply whereas in List it will create that many times.
2. In Arrays we have to use similar datatypes whereas in List we can use different datatypes.

# import numpy library

In [1]:
import numpy as np

# To print array

In [8]:
#List
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
#Tuples
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in array

# 0-D Array

In [12]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim) # To know dimension of an array

20
<class 'numpy.ndarray'>
0


# 1-D Array

In [13]:
# 1-D array
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


# 2-D Array

In [15]:
# 2-D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


# 3-D Array

In [18]:
# 3-D array
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [3]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions

In [4]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6],[6,7,8]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimenssional Arrays
An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndim argument.

# Create an array with 5 dimensions and verify that it has dimensions:

In [7]:
arr = np.array([1,2,3,4], ndmin = 5)

print(arr)
print('Number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions : 5


In [8]:
a = np.array([[[[[1,2,3,4,5,6]]]]])
print(a)
print(a.ndim)

[[[[[1 2 3 4 5 6]]]]]
5


# NumPy Array Indexing
1. Array Indexing is same as accessing an array element.
2. You can access an array element by reffereing to its index number.
3. The indexes in NumPy array starts with 0, meaning that the first element has index 0, and the second has index 1 etc.

# Get the first element from the following array:

In [10]:
arr = np.array([1,2,3,4])
print(arr[0])

1


# Get third and sixth and eighth. elements from the following array and add them.

In [12]:
m = np.array([41,87,34,56.8,39.23,90,15,10,19,56])
print("The third element is: ", m[2])
print("The sixth element is: ", m[5])
print("The eighth element is: ", m[7])
print("The Sum of elements are: ", m[2]+m[5]+m[7])

The third element is:  34.0
The sixth element is:  90.0
The eighth element is:  10.0
The Sum of elements are:  134.0


# Slicing of numpy arrays

In [13]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [18]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])
#print(arr[0:7:2])

[1 3 5 7]


# Slicing in 2-D array

In [19]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[1,1:4])

[70 80 90]


In [20]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[0,0:3])

[10 20 30]


# Checking the datatype of an array

In [21]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [22]:
arr = np.array(['animals','bat','cat'])
print(arr.dtype)

<U7


# Creating arrays with a defined data type

In [24]:
arr = np.array([1,2,3,4], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


# Create an array with data types 4 bytes integer

In [26]:
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# Numpy array Shape
The shape of an array is the number of elements in each dimension.

# Print the shape of a 2-D array

In [28]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [32]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr.shape)

(1, 3, 4)


# Joining Numpy Arrays

In [34]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


# Join 2-D Arrays


# Row Axis

In [38]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Column Axis

In [39]:

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Splitting Numpy Arrays

# Splitting the array in 3 parts

In [40]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# Splitting the array in 4 parts

In [41]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Unique Function

In [42]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
[ 1  2  3  4  5  6  7  9 12 22 33]


# Unique Element along with its index

In [43]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 15,  6,  2,  8,  3,  4,  5,  0,  9, 10], dtype=int64))


# Delete

In [45]:
a = np.array([12,13,14,15])
d = np.delete(a, [1])
print(d)

[12 14 15]


In [46]:
x = np.array([[2,7,9,6,8], [4,5,7,1,2], [50,0,65,6,7]])
print(x)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [50  0 65  6  7]]


In [47]:
# delete [ 4  5  7  1  2]
m = np.delete(x, 1, axis = 0)
print(m)

[[ 2  7  9  6  8]
 [50  0 65  6  7]]
