In [3]:

import numpy as np

In [68]:
lst=[1,2,3,4]
print(lst*3)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [69]:
lst=[1,2,3,4]
arr=np.array(lst)

In [70]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4])

In [ ]:
# one bracket in opening & 1 bracket in closing so it a 1d array
if it is 1D array then it will show how many numbers of elsements are there

In [8]:
arr.shape

(4,)

In [71]:
mylst1=[1,2,3,4,5]
mylst2=[4,5,6,7,8]
mylst3=[5,6,7,8,9]
arr=np.array([mylst1,mylst2,mylst3])

In [72]:
arr

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [73]:
arr.shape

(3, 5)

In [ ]:
2 d array bcoz 2 opening bracket & 2 as closing.

In [76]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 4],
       [5, 6, 7],
       [8, 5, 6],
       [7, 8, 9]])

In [77]:
lst=[1,2,3,4,5]
arr=np.array(lst)

In [78]:
arr

array([1, 2, 3, 4, 5])

In [79]:
 arr[3]

4

In [80]:
mylst1=[1,2,3,4,5]
mylst2=[4,5,6,7,8]
mylst3=[5,6,7,8,9]
arr=np.array([mylst1,mylst2,mylst3])

In [82]:
arr

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [83]:
arr[1,3]

7

In [84]:
arr=np.arange(0,11)


In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr=np.arange(0,10,2)

In [93]:
arr

array([0, 2, 4, 6, 8])

In [97]:
np.linspace(5,100,20)

array([  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
        60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [98]:
 arr=np.array([1,2,3,4,5,6,7])


In [101]:
arr[1:5]

array([2, 3, 4, 5])

In [102]:
arr[3:]=100

In [106]:
arr

array([  1,   2,   3, 100, 100, 100, 100])

In [107]:
arr1=arr

In [108]:
arr1

array([  1,   2,   3, 100, 100, 100, 100])

In [109]:
arr1[3:]=500

In [110]:
arr1

array([  1,   2,   3, 500, 500, 500, 500])

In [48]:
arr

array([  1,   2,   3, 500, 500, 500, 500])

In [49]:
arr1=arr.copy()

In [50]:
arr1[3:]=700

In [51]:
arr

array([  1,   2,   3, 500, 500, 500, 500])

In [52]:
arr1<2

array([ True, False, False, False, False, False, False])

In [112]:
arr1*2

array([   2,    4,    6, 1000, 1000, 1000, 1000])

In [53]:
arr1*2

array([   2,    4,    6, 1400, 1400, 1400, 1400])

In [54]:
arr1[arr1<2]

array([1])

In [55]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [56]:
table=pd.DataFrame(np.arange(0,20).reshape(4,5),index=['R1','R2','R3','R4'],columns=['C1','C2','C3','C4','C5'])

In [57]:
table

C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19

In [ ]:
access elements
.loc,iloc

In [58]:
table.loc['R1']

C1    0
C2    1
C3    2
C4    3
C5    4
Name: R1, dtype: int32

In [59]:
type(table.loc['R1'])

pandas.core.series.Series

In [ ]:
series can be only one row or one column.

In [62]:
table.iloc[:,:]

C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19

In [64]:
# convert data frames in to arrays
table.iloc[:,:].values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [67]:
table['C1'].value_counts()

0     1
5     1
10    1
15    1
Name: C1, dtype: int64

In [123]:
import pandas as pd
satyam1=pd.DataFrame(np.arange(0,16).reshape(4,4),index=["R1","R2","R3","R4"],columns=["C1","C2","C3","C4"])
satyam1

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7
R3   8   9  10  11
R4  12  13  14  15

In [ ]:
# import pandas as pd
# satyam1=pd.DataFrame(np.arange(0,16).reshape(1,16),index=["R1"],columns=["C1","C2","C3","C4"])
# satyam1